sensor:
  - platform: total_daily_energy
    name: "${upper_devicename} Energy Today"
    power_id: power_wattage
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:lightning-bolt

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO04
    change_mode_every: 4
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    update_interval: 3s

    current:
      name: "${upper_devicename} Current"
      unit_of_measurement: A
      accuracy_decimals: 3
      icon: mdi:current-ac

    voltage:
      name: "${upper_devicename} Voltage"
      unit_of_measurement: V
      accuracy_decimals: 1
      icon: mdi:current-ac

    power:
      name: "${upper_devicename} Power"
      unit_of_measurement: W
      id: power_wattage
      icon: mdi:flash
